### ISSUE TITLE
make website reachable ENS

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-website#111]
the walletconnect website should be reachable via ENS

**Comment by pedrouid** [comment]
Just used fleek to do this 👍 

ipfs://QmSUAg7GvEFCZ2ASsoh83MRQDhjPpzP2G83ySXTPUL7gJY

ipfs://bafybeib5loza45z65ivtzrbpqn4dokckwur5adyjg37cexturd67dcyd6u/
