### ISSUE TITLE
Website still advertises Telegram

### ISSUE THREAD

**Issue by comodoro** [WalletConnect/walletconnect-website#118]
After going through the hassle of connecting to Telegram and using up a SIM I got a message that Telegram is no longer supported. It would be a good idea to remove the Telegram link from the website.

**Comment by pedrouid** [comment]
Sorry about that! I will update it now

**Comment by pedrouid** [comment]
Thanks for notifying us 👍 removed from the website and documentation

**Comment by comodoro** [comment]
Thanks for the super quick reaction:-)

pá 19. 2. 2021 v 18:09 odesílatel Pedro Gomes <notifications@github.com> napsal:
