### ISSUE TITLE
[Request] Adding the Enjin Wallet to the portfolio

### ISSUE THREAD

**Issue by ShadowFM** [WalletConnect/walletconnect-website#127]
Hey guys,
I would really like if you could add the Enjin Wallet: https://enjin.io/software/wallet
It's a mobile wallet of Android and iOS.

https://enjin.io/help-center-category/wallet

Thanks!
Shadow

**Comment by pedrouid** [comment]
App submissions should be done here: https://github.com/WalletConnect/walletconnect-registry
