### ISSUE TITLE
Change the Unstoppable Wallet logo 

### ISSUE THREAD

**Issue by Dadybayo** [WalletConnect/walletconnect-website#132]
WalletConnect added the Unstoppable wallet in December 2020. But for some unknown reason, our logo has been changed to a different one. Could you please change our logo? 

https://github.com/horizontalsystems/HS-Design -- Press Kit

**Comment by pedrouid** [comment]
my bad! you are right this was a mistaken on my end

**Comment by pedrouid** [comment]
Fixed on commit: https://github.com/WalletConnect/walletconnect-registry/commit/05249529f5ea6eeb2d917cba890380033196abd3
