### ISSUE TITLE
Add docs page

### ISSUE THREAD

**Issue by ricburton** [WalletConnect/walletconnect-website#2]
![balance-api-docs](https://user-images.githubusercontent.com/438160/38764324-93d043aa-3f7a-11e8-9a0a-4c0487534e47.png)

**Comment by ricburton** [comment]
Here are the raw design files: https://cl.ly/3d2h340Q2c3p

**Comment by davidjryan** [comment]
More than happy to do this if you are willing to assign it to me.

**Comment by ricburton** [comment]
![walletconnect-api-docs](https://user-images.githubusercontent.com/438160/40590929-d5396194-61ff-11e8-97d0-9469287311d8.png)
