### ISSUE TITLE
One video is worth of thousand pictures

### ISSUE THREAD

**Issue by miohtama** [WalletConnect/walletconnect-website#60]
As WalletConnect concept is still new, especially to the end-users, it might make sense to do some PR and education effort on the website. Especially now when WalletConnect is gaining traction and the community is facing more direct end user conversations. I would propose doing an animation or a live acting demo video that shows the two use cases

- From a dApp web page to a mobile wallet
- From a desktop browser to a mobile wallet

... and then have this video on the landing page.

Videos take more effort, but they are impactful especially with the international audience with weaker English skills. 

Now my question is that it might take some co-ordination to get this forward. We would probably need to write a script and then source an animator or a professional video editor to make it slick. If we can find one from Ethereum community that would be great. 

Asking a feedback on this idea here.

**Comment by pedrouid** [comment]
There is a actually an old video but I guess. you mean something more informative and perhaps animated
