### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by ricburton** [WalletConnect/walletconnect-website#8]
Boring but important

**Comment by miohtama** [comment]
I think it might not be needed.

The website does not have tracker or users.

Any user do not have relationship with WalletConnect Association. 

Any privacy policy users need to sign is with wallet providers and Dapps.

**Comment by pedrouid** [comment]
Yeah I discussed recently with Gnosis legal advisor as well and WalletConnect's protocol doesn't have any data at all so the policy is not actually needed
