### ISSUE TITLE
Extend dapp information

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-website#89]
I think it would be great to add the following infos to dApps:
 * chains used
 * EIPs used

what do you think?

**Comment by bmann** [comment]
Category. Also wish list! I really want xdaichain to support WalletConnect! And Circles!

**Comment by ligi** [comment]
I would also love to see WalletConnect support for circles. But as far as I see xDAI should already be supported by WC - just another EVM compatible chain with a chainID - don't see another change that needs to be made for WC here - or am I missing something?

**Comment by bmann** [comment]
If you go to https://bridge.xdaichain.com/ it shows no wallet found and doesn’t have a WC option. I was trying to swap DAI for xDAI and couldn’t do it at all on mobile. 

Circles could support a WC login for advanced users. Could be coming in the future. 

Not support at the protocol level but actually enabled and an option in the dapp. 

A wish list could show support for “please add WC to this dapp”

**Comment by pedrouid** [comment]
Currently I'm building a registry that will tackle this problem: https://github.com/WalletConnect/walletconnect-registry
